networks:
  cassandra:
    driver: bridge

services:
  node1:
    image: cassandra:5.0
    container_name: cassandra1
    hostname: h1
    restart: on-failure
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 5s
        timeout: 5s
        retries: 60
    networks:
      - cassandra
    ports:
      - "9042:9042"
    volumes:
      - ./tmp/cassandra1:/var/lib/cassandra
      #- ./etc/cassandra1:/etc/cassandra
    environment: &environment
        CASSANDRA_SEEDS: cassandra1,cassandra2
        CASSANDRA_CLUSTER_NAME: Virgo
        CASSANDRA_DC: MilkyWay
        CASSANDRA_RACK: R1
        CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
        CASSANDRA_NUM_TOKENS: 128
        MAX_HEAP_SIZE: 512M
        HEAP_NEWSIZE: 256M
  node2:
    image: cassandra:5.0
    container_name: cassandra2
    hostname: h2
    restart: on-failure
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 5s
        timeout: 5s
        retries: 60
    networks:
      - cassandra
    ports:
      - "9043:9042"
    volumes:
      - ./tmp/cassandra2:/var/lib/cassandra
      #- ./etc/cassandra2:/etc/cassandra
    environment: *environment
    depends_on:
      node1:
        condition: service_healthy

  node3:
    image: cassandra:5.0
    container_name: cassandra3
    hostname: h3
    restart: on-failure
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 5s
        timeout: 5s
        retries: 60
    networks:
      - cassandra
    ports:
      - "9044:9042"
    volumes:
      - ./tmp/cassandra3:/var/lib/cassandra
      #- ./etc/cassandra3:/etc/cassandra
    environment: *environment
    depends_on:
      node2:
        condition: service_healthy

  node4:
    image: cassandra:5.0
    container_name: cassandra4
    hostname: h4
    restart: on-failure
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 5s
        timeout: 5s
        retries: 60
    networks:
      - cassandra
    ports:
      - "9045:9042"
    volumes:
      - ./tmp/cassandra4:/var/lib/cassandra
      #- ./etc/cassandra4:/etc/cassandra
    environment: *environment
    depends_on:
      node3:
        condition: service_healthy


